name: ci-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.18', '1.x' ]
        gostable: [true]
        include:
        - go: '1.x'
          gostable: false
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/k8s.io/kube-openapi/

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "${{ matrix.go }}"
        stable: ${{ matrix.gostable }}"

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}/src/k8s.io/kube-openapi/
        go mod tidy && git diff --exit-code
        go build ./cmd/... ./pkg/...
    - name: Format
      run: |
        diff=$(gofmt -s -d .)
        if [[ -n "${diff}" ]]; then echo "${diff}"; exit 1; fi
    - name: Test
      run: |
        cd ${GITHUB_WORKSPACE}/src/k8s.io/kube-openapi/
        GOPATH=${GITHUB_WORKSPACE} go test ./cmd/... ./pkg/...
    - name: Run integration tests
      run: |
        cd ${GITHUB_WORKSPACE}/src/k8s.io/kube-openapi/test/integration
        go mod tidy && git diff --exit-code
        GOPATH=${GITHUB_WORKSPACE} go test ./...
  required:
    # The name of the ci jobs above change based on the golang version.
    # Use this as a stable required job that depends on the above jobs.
    # ref: https://github.com/kubernetes/test-infra/pull/27016
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - run: echo "Required jobs success!"
